name: Main branch CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  lint-report:
    uses: ./.github/workflows/lint-report.yaml

  build-check:
    uses: ./.github/workflows/build-check.yaml
